# -*- coding: utf-8 -*-
"""caesar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1At0ZnUBZSNBzgAHsXcEQaYnWdWjnuYDS
"""

def cifrulCezar(text, k, criptare =True):
  rezultat = ""

  if not criptare:
    k = -k

  for char in text:
    if char.isalpha():
      start = ord('A') if char.isupper() else ord('a')
      rezultat += chr((ord(char)- start+k) % 26 + start)
    else:
      rezultat += char
  return rezultat

text_original = input("Textul pentru criptat: ")
k = 3
text_criptat= cifrulCezar(text_original, k, criptare = True)
text_decriptat = cifrulCezar(text_criptat, k , criptare= False)
print("Text criptat: ", text_criptat)
print("Text decriptat: ", text_decriptat)