# -*- coding: utf-8 -*-
"""ElGamal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NGvqAnB9t92bk60mMHUZB292D5V_jn_G
"""

import random
from math import sqrt

def test_primalitate(n):
  if n <= 1:
    return False
  else:
    nrDiv = 0
    for potential_divizor in range(2, int(sqrt(n)) +1):
      if n % potential_divizor == 0:
        nrDiv = nrDiv +1
    if nrDiv == 0:
      return True
    else:
      return False

def generare_aleatoare_nr_prim(a,b):
  p = random.randint(a,b)
  while test_primalitate(p) == False:
    p = random.randint(a,b)
  return p

def cmmdc(a,b):
  while a != b:
    if a > b:
      a = a - b
    else:
      b = b - a
  return a

def genereaza_cheie_privata(p):
  x = random.randint(2, p - 2)
  return x

def genereaza_cheie_publica(p, g, x):
  y = pow(g , x, p)
  return y

def verificare_generator(g,p):
  #orice generator trebuie sa aiba ordinul p-1 in grupul Z_p (adica g^{p-1} mod p ==1)
  if pow(g, p-1, p) != 1:
    return False
  else:
    for i in range(1, p-1):
      if pow(g, i, p) == 1:
        return False
    return True

def divizori_primi(n):
    divizori = set()
    d = 2
    while d * d <= n:
        while n % d == 0:
            divizori.add(d)
            n = n // d
        d ==  d+ 1
    if n > 1:
        divizori.add(n)
    return divizori

def este_generator(g, p):
    factori = divizori_primi(p - 1)
    for q in factori:
        if pow(g, (p - 1) // q, p) == 1:
            return False
    return True


def generare_generator (p):
  g = random.randint(2, p - 1)
  while verificare_generator(g,p) == False:
    g = random.randint(2, p - 1)
  return g


def criptare_ElGamal(text_original,p,g,y): #p,g,y
    text_criptat = []
    k = random.randint(2, p - 2)
    c1 = pow(g, k, p)
    c2 = pow(y, k, p)
    for caracter in text_original:
      m = ord(caracter)
      c = (m * c2) % p
      text_criptat.append(c)
    return text_criptat, c1

def decriptare_ElGamal(c1, text_criptat,x,p):
    text_decriptat = ""
    s = pow(c1, x, p)
    s_inv = pow(s,-1, p)
    for c in text_criptat:
        caracter = chr((c * s_inv) % p)
        text_decriptat += caracter
    return text_decriptat

"""Test"""

p = generare_aleatoare_nr_prim(2000,3000)
g = generare_generator(p)
cheie_privata = genereaza_cheie_privata(p)
cheie_publica = genereaza_cheie_publica(p, g, cheie_privata)

mesaj_original = input("Mesajul pentru criptare: ")
print("Mesaj original:", mesaj_original)

mesaj_criptat, c1 = criptare_ElGamal(mesaj_original, p, g, cheie_publica)
print("Mesaj criptat:", mesaj_criptat)

mesaj_decriptat = decriptare_ElGamal(c1, mesaj_criptat, cheie_privata, p)
print("Mesaj decriptat:", mesaj_decriptat)