# -*- coding: utf-8 -*-
"""Polybius.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ju6oCAinxBkvFbJhD0EmmK89zDJUbhD4
"""

#Cifrul lui Polybius fara cheie

def generare_patrat_polybius():
  alfabet = "ABCDEFGHIKLMNOPQRSTUVWXYZ" # Am omis J
  patrat = {}
  index = 0

  for linie in range(1, 6):
    for coloana in range(1, 6):
      patrat[alfabet[index]] = f"{linie}{coloana}"
      index += 1

  patrat[" "] = "00"
  return patrat

def criptare_polybius(text):
  patrat = generare_patrat_polybius()
  text = text.upper().replace("J", "I")
  text_criptat = []

  for character in text:
    if character in patrat:
      text_criptat.append(patrat[character])
    else:
      text_criptat.append(character)

  return " ".join(text_criptat)

def decriptare_polybius(text_criptat):
  patrat = generare_patrat_polybius()
  patrat_inv = {v: k for k, v in patrat.items()}
  text_decriptat = []

  for pereche in text_criptat.split():
    if pereche in patrat_inv:
      text_decriptat.append(patrat_inv[pereche])
    else:
      text_decriptat.append(pereche)

  return "".join(text_decriptat)

text_original = "MESAJ SECRET"
text_criptat = criptare_polybius(text_original)
text_decriptat = decriptare_polybius(text_criptat)

print("Text original: ", text_original)
print("Text criptat: ", text_criptat)
print("Text decriptat: ", text_decriptat)