# -*- coding: utf-8 -*-
"""XTEA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13iLWJPi-ec67ubkhXCAHWJFvi4b3ucMF
"""

import os

def criptare_XTEA_bloc(block, key):

  block1 = b''
  block2 = b''
  for byte in range(0, 4):
    block1 += bytes([block[byte]])
  for byte in range(4,8):
    block2 += bytes([block[byte]])

  v0 = int.from_bytes(block1, 'big')
  v1 = int.from_bytes(block2, 'big')

  key0 = key[0]
  key1 = key[1]
  key2 = key[2]
  key3 = key[3]
  delta = 0x9E3779B9
  sum = 0


  for round in range(32):
      sum = (sum + delta) & 0xFFFFFFFF
      v0 = (v0 + (((v1 << 4 ^ v1 >> 5) + v1) ^ (sum + key[sum & 3]))) & 0xFFFFFFFF
      v1 = (v1 + (((v0 << 4 ^ v0 >> 5) + v0) ^ (sum + key[(sum >> 11) & 3]))) & 0xFFFFFFFF

  v0_bytes = v0.to_bytes(4,'big')
  v1_bytes = v1.to_bytes(4,'big')

  return v0_bytes + v1_bytes

def decriptare_XTEA_bloc(block, key):

  block1 = b''
  block2 = b''
  for byte in range(0, 4):
    block1 += bytes([block[byte]])
  for byte in range(4,8):
    block2 += bytes([block[byte]])

  v0 = int.from_bytes(block1, 'big')
  v1 = int.from_bytes(block2, 'big')

  key0 = key[0]
  key1 = key[1]
  key2 = key[2]
  key3 = key[3]
  delta = 0x9E3779B9
  sum = (delta << 5) & 0xFFFFFFFF


  for round in range(32):
    v1 = (v1 - (((v0 << 4 ^ v0 >>5) + v0) ^ (sum + key[(sum >> 11) & 3]))) & 0xFFFFFFFF
    v0 = (v0 - (((v1 << 4 ^ v1 >>5) + v1) ^ (sum + key[sum & 3]))) & 0xFFFFFFFF
    sum = (sum - delta) & 0xFFFFFFFF

  v0_bytes = v0.to_bytes(4,'big')
  v1_bytes = v1.to_bytes(4,'big')

  return v0_bytes + v1_bytes

def imparte_in_blocuri_de_8_bytes(mesaj):
    lista_blocuri = []
    mesaj_bytes = mesaj.encode('utf-8')

    i = 0
    rest = len(mesaj_bytes) % 8
    while i + 8 < len(mesaj_bytes):
      bloc = b''
      for index in range(i,i+8):
        bloc += bytes([mesaj_bytes[index]])
      lista_blocuri.append(bloc)
      i = i + 8

    if rest != 0:
      bloc = b''
      for index in range(i , i + rest):
        bloc += bytes([mesaj_bytes[index]])

      nr_spatii_necesar = 8 - len(bloc)
      for spatiu in range(0, nr_spatii_necesar):
        bloc += b' '

      lista_blocuri.append(bloc)
    return lista_blocuri



def generate_key():
    random_key = os.urandom(16)
    key = []

    index = 0
    while index < 16:
      subcheie = b''
      for byte in range(index,index + 4):
        subcheie += bytes([random_key[byte]])
      subkey = int.from_bytes(subcheie, 'big')
      key.append(subkey)
      index = index + 4

    return key

mesaj = input("Introdu mesajul de criptat: ")

key = generate_key()
print("Cheie: ", hex(key[0]) , hex(key[1]), hex(key[2]), hex(key[3]))

# Împărțim mesajul în blocuri de 8 bytes
list_original_blocks = imparte_in_blocuri_de_8_bytes(mesaj)

# Criptare
lista_blocuri_criptate = []
mesaj_criptat = b''
for block in list_original_blocks:
  bloc_criptat = criptare_XTEA_bloc(block, key)
  lista_blocuri_criptate.append(bloc_criptat)
  mesaj_criptat += bloc_criptat
print("Mesaj criptat (afisat in hexazecimal):", mesaj_criptat.hex())

#Decriptare
mesaj_decriptat = b''
for block in lista_blocuri_criptate:
  bloc_decriptat = decriptare_XTEA_bloc(block,key)
  mesaj_decriptat += bloc_decriptat
print("Mesaj decriptat:" , mesaj_decriptat.decode('utf-8'))