# -*- coding: utf-8 -*-
"""affine_cipher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2dw-IMX6WbO3SFj5poPWwoMLBZR7Tyw
"""

def cmmdc(a:int, b:int)->int:
  while a!=b:
    if a>b :
      a = a-b
    else:
      b = b-a
  return a

def criptare_afina(text, a,b, l_alfabet):
  if cmmdc(a, l_alfabet) >1:
    return "Cheie incorecta"

  rezultat = ""
  for char in text:
        if char.isalpha():
            start = ord('A') if char.isupper() else ord('a')
            Pi = ord(char) - start
            Ci = (a * Pi + b) % l_alfabet
            rezultat += chr(Ci + start)
        else:
            rezultat += char

  return rezultat

def decriptare_afina(text, a,b, l_alfabet):
  A = pow(a, -1, l_alfabet)
  B = (-b * A) % 26
  return criptare_afina(text,A,B,l_alfabet)

text_original = input("Text original: ")
text_criptat = criptare_afina(text_original, 3, 5, 26)
text_decriptat = decriptare_afina(text_criptat, 3,5,26)

print(text_criptat)
print(text_decriptat)

print(criptare_afina("PRIMAVARA INCEPE",3,5,26))
print(decriptare_afina("YEDPFQFEF DSLRYR",3,5,26))
