# -*- coding: utf-8 -*-
"""Trithemius.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFJMByum2b4jy_N6NZ_wUfzm4lIyDgHa
"""

def creare_tabula_recta():
    alfabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    tabel = []

    for decalare in range(26):
        linie = []  # Creăm fiecare linie

        for i in range(26):
            index = (i + decalare) % 26  # Calculăm poziția pentru fiecare literă
            linie.append(alfabet[index])  # Adăugăm litera în linie

        tabel.append(linie)  # Adăugăm linia în tabel

    return tabel

def afisare_tabula_recta(tabel):
    for linie in tabel:
        print(" ".join(linie))

# Creăm tabula recta și o afișăm
tabula = creare_tabula_recta()
afisare_tabula_recta(tabula)

def criptare_trithemius(text):
    alfabet = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    tabula_recta = creare_tabula_recta()
    text = text.upper()
    text_criptat = ""
    i = 1

    for char in text:
        if char in alfabet:
            index_alfabet = alfabet.index(char)
            coloana = index_alfabet
            linie = i % 26
            litera_criptata = tabula_recta[linie][coloana]
            text_criptat += litera_criptata
            i += 1
        else:
            text_criptat += char

    return text_criptat


def decriptare_trithemius(text_criptat):
  alfabet= list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
  tabula_recta = creare_tabula_recta()
  text_decriptat = ""
  i = 1
  for caracter in text_criptat:
    if caracter in alfabet:
      linie = i%26
      for j in range(0,26):
        if caracter == tabula_recta[linie][j]:
          index_coloana = j
        else:
          j= j+1
      litera_decriptata = alfabet[index_coloana]
      text_decriptat += litera_decriptata
      i = i +1

    else:
      text_decriptat += caracter

  return text_decriptat


mesaj= "TREBUIE SA INVINGEM ASTAZI SEARA"
print(f"Text original: ", mesaj)
print(f"Text criptat: ", criptare_trithemius(mesaj))
print(f"Text decriptat: ", decriptare_trithemius(criptare_trithemius(mesaj)))
